taosdata/taos-tools

src/benchOutput.c, src/taosdump.c
=> remove oem infos

packaging/deb/make-taos-tools-deb.sh, packaging/tools/install-taostools.sh, packaging/tools/make_install.sh, packaging/tools/uninstall-taostools.sh
[TS-1166]<release>: change for release script
=> [TS-1166]<release>: change for release script

src/taosdump.c, taosbenchmark-user-manual.md
fix keep for enterprise edition
=> [TD-13052]<feature>: taosdump prepare for 3.0

src/taosdump.c
=> <fix>: taosdump mem still reachable

README-CN.md, README.md, src/CMakeLists.txt
=> fix: add more OS id

src/taosdump.c
=> fix: resource leak found by coverity scan

packaging/deb/make-taos-tools-deb.sh, packaging/rpm/taos-tools.spec
=> enh: move taosdemo out from taosTools

.github/workflows/commitlint.yml
=> feat: add commit lint action

src/benchData.c, src/benchInsert.c
=> fix: memory failure when big number subtable

inc/benchData.h, src/benchData.c, src/benchInsert.c
=> fix: use 64 bit int to support large num subtables

src/taosdump.c
=> refactor: use max int64 to replace -1 for unlimit

src/taosdump.c
=> chore: refine taosdump help output

src/taosdump.c
order by should not used with count()
[TD-13052]
=> feat: taosdump prepare for 3.0

src/taosdump.c
=> fix: taosdump incorrect count when dump in

src/CMakeLists.txt
=> chore: support build taosdump on rhel

src/taosdump.c
on default thread num
[TD-16583]
=> fix: taosdump help output mistake

src/taosdump.c
=> feat: taosdump support inspect avro file

.github/workflows/cmake-release-ws.yml
add .github/workflows/cmake-release-ws.yml
=> feat: prepare for 3.0

.github/workflows/3.0-taosdump-release-ws.yml, packaging/rpm/taos-tools.spec
fix: 3.0-taosdump-release-ws.yml install for push
=> fix: taostools uninstall

.github/workflows/3.0-taosdump-release-ws.yml, .github/workflows/3.0-taosdump-release.yml, src/taosdump.c, tests/pytest/util/dnodes.py
initial work to reduce buffer overflow
=> feat: taosdump support multiple directories

.github/workflows/3.0-coveralls.yml, .github/workflows/ci-taosdump-debug.yml, .github/workflows/coveralls.yml, src/taosdump.c, tests/taosdump/native/taosdumpTestInspect.py
This reverts commit 2cdc717805dd4b2514176b696c7a933154d3f37a.
=> Revert "feat: taosdump use directories (#354)"

src/benchInsert.c, src/benchJsonOpt.c, src/benchUtil.c
change iface to taosc if websocket
=> fix: taosbenchmark stmt init

src/taosdump.c, tests/taosdump/native/taosdumpTestLooseMode.py
https://github.com/taosdata/taos-tools/issues/398
=> fix: taosdump loose mode dump table with single tag

.github/workflows/3.0-coveralls.yml, .github/workflows/3.0-windows-build.yml, src/benchMain.c, src/taosdump.c
need to export RUST_LOG=debug and use -g
=> chore: taosbenchmark enable ws log

.github/workflows/2.x-taosdump-debug.yml, .github/workflows/2.x-taosdump-release.yml, src/taosdump.c, tests/taosdump/native2/taosdumpTest64Krow.py
expand avro writer->len to 70k
=> fix: taosdump supports 64k row

README.md
update download links to tdengine to the correct url
=> docs: update links in github readme

inc/toolsdef.h, src/benchInsert.c
Reverts taosdata/taos-tools#751
=> Revert "Feat/td 30267" taosGetTotalMemory not found
